# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 15:28
from __future__ import unicode_literals

import database.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=database.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_inicio', models.DateTimeField(verbose_name='data e horário de inicio')),
                ('t_fim', models.DateTimeField(verbose_name='data e horário de fim')),
                ('n_total', models.PositiveSmallIntegerField(default=5)),
                ('n_atual', models.PositiveSmallIntegerField(default=1)),
                ('local', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('turma', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('periodo', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('materia_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Materia')),
            ],
        ),
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='URLs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='')),
                ('recurso_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Recursos')),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='periodo_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Periodo'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='materia_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Materia'),
        ),
        migrations.AddField(
            model_name='fotos',
            name='recurso_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Recursos'),
        ),
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together=set([('codigo', 'turma')]),
        ),
    ]
