# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='materia_key',
        ),
        migrations.AddField(
            model_name='materia',
            name='nome',
            field=models.CharField(default='me dê um nome de verdade', max_length=40),
        ),
        migrations.AddField(
            model_name='periodo',
            name='periodo_nome',
            field=models.CharField(default='2000.1', max_length=6),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='periodo',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
