# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20171024_1410'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotos',
            new_name='Foto',
        ),
        migrations.RenameModel(
            old_name='Recursos',
            new_name='Recurso',
        ),
        migrations.RenameModel(
            old_name='URLs',
            new_name='URL',
        ),
    ]
