# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20171024_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='periodo_key',
            field=models.ForeignKey(default=20001, on_delete=django.db.models.deletion.PROTECT, to='database.Periodo'),
        ),
        migrations.RemoveField(
            model_name='materia',
            name='url',
        ),
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together=set([('codigo', 'turma', 'periodo_key')]),
        ),
    ]
