# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20171025_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(max_length=2)),
                ('materia_key', models.ForeignKey(default=20001, on_delete=django.db.models.deletion.PROTECT, to='database.Materia')),
                ('periodo_key', models.ForeignKey(default=20001, on_delete=django.db.models.deletion.PROTECT, to='database.Periodo')),
            ],
        ),
    ]
