# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_dataprova'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='materia_key',
            field=models.ForeignKey(default='AAA00000', on_delete=django.db.models.deletion.PROTECT, to='database.Materia'),
        ),
    ]
