# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_recurso_materia_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprova',
            name='data',
            field=models.DateField(default='1900-1-1'),
        ),
        migrations.AddField(
            model_name='dataprova',
            name='prova',
            field=models.CharField(default='VS', max_length=2),
        ),
    ]
