# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20171025_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='date',
            field=models.DateField(default='1900-1-1'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='t_fim',
            field=models.TimeField(default='22:00'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='t_inicio',
            field=models.TimeField(default='9:00'),
        ),
    ]
